name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar en Release
        run: dotnet build --configuration Release --no-restore

      - name: Publicar
        run: dotnet publish Facturacion.WebApi/Facturacion.WebApi.csproj --configuration Release --output ./publish --no-build

      - name: Deploy via Zip Deploy
        run: |
          cd ./publish
          zip -r ../app.zip .
          cd ..
          curl -X POST \
            --user "${{ secrets.AZURE_APP_USERNAME }}:${{ secrets.AZURE_APP_PASSWORD }}" \
            --data-binary @app.zip \
            "https://facturacionnv-cdgdhvh8b3gfarcm.scm.canadacentral-01.azurewebsites.net/api/zipdeploy"
